fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
    body_listener:
        array_normalizer: fos_rest.normalizer.camel_keys
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: validationErrors
    view:
        view_response_listener:  true
    exception:
        codes:
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [ json ] }
